name: CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Exécuter les tests
        run: |
          pytest tests/
